project:
  type: website

website:
  title: "a.j.l."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - "posts/visualization/index.qmd"
      - "posts/photography/index.qmd"
      - about.qmd
format:
  html:
    theme: minty2.scss
    css: styles.css

listing:
  contents: "posts/*/index.qmd"



