project:
  type: website
  output-dir: docs

website:
  title: "a.j.l."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - "posts/visualization/index.qmd"
      - "posts/photography/index.qmd"
      - "posts/about/index.qmd"
format:
  html:
    theme: minty2.scss
    css: styles.css
toc: true
listing:
  contents: "posts/*/index.qmd"


