project:
  type: website
  output-dir: docs

website:
  title: "a.j.l."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
format:
  html:
    theme: bunyan.scss
    css: styles.css
    toc: true
    page-layout: full



