project:
  type: website
  output-dir: docs

website:
  title: "andrewjliang.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full



