---
title: "About"
description: A little more about me!
author: Andrew Liang
date: 6/5/2024
categories: [about, personal]
bibliography: references.bib
---

I was born in Hayward, California, but have lived in neighboring Fremont for much of my life. As a kid, I had multiple interests:

-   riding the [Bay Area Rapid Transit (BART)](bart.gov) system (and maybe becoming a train operator for it someday),
-   computers,
-   baseball, and
-   becoming the President of the United States.

I gave up the first and third options pretty quickly, because I realized that (1) constantly asking your parents to take you on weekly rides on BART wasn't an economically or academically smart choice when I turned 5, and (2) becoming the President of the United States opens you to new challenges that I thought I would not take well. I gave up studying computers after I realized I barely understood [@computer1994]. Finally, my fastball in fifth grade was clocked in at under 40 miles per hour. Thus, all of those interests eventually faded from view.
